# Generated by Django 3.2.3 on 2021-05-13 15:34

from django.db import migrations, models
import page.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50)),
                ('random_id', models.IntegerField(default=page.models.random_integer)),
            ],
        ),
    ]
